spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=liquibase;encrypt=true;trustServerCertificate=true
    username: user
    password: yesh@6289
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  jpa:
    hibernate:
      ddl-auto: none # Use 'none' when using Liquibase to manage schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
    contexts: development

  logging:
    level:
      root: WARN